### ISSUE TITLE
The Chinese Translation [not by me]

### ISSUE THREAD

**Issue by THETATATA** [rempAut/PZ-ClothingUI#18]
Hey I m coming help steam the chinese's workers just done for CN translation but he dont know how use github.
So I m just came here copy his/her reply here for help :)
Hope I didn't do anything bad :)

@pagep , ok, Simplified Chinese translation filename: UI_CN.txt

UI_CN = {
UI_CUI_window_title = "装备物品",
UI_CUI_no_items_avaliable = "库存中无可用的物品",

-- Category Buttons
UI_CUI_Category_HEAD = "头",
UI_CUI_Category_UNDIES = "内衣",
UI_CUI_Category_BODY = "身体",
UI_CUI_Category_HANDS = "手",
UI_CUI_Category_LEGS = "腿",
UI_CUI_Category_FEET = "脚",
UI_CUI_Category_ACC = "扣带",
UI_CUI_Category_TRINKET = "饰品",

-- Body slots naming
UI_CUI_FannyPackFront = "前腰包",
UI_CUI_FannyPackBack = "后腰包",
UI_CUI_Hat = "帽子",
UI_CUI_Mask = "面罩",
UI_CUI_FullHat = "全帽",
UI_CUI_MaskEyes = "眼罩面罩",
UI_CUI_MaskFull = "全面罩",
UI_CUI_FullHelmet = "头盔",
UI_CUI_Jacket = "外套",
UI_CUI_FullTop = "外部套装",
UI_CUI_JacketHat = "连帽外套",
UI_CUI_Sweater = "毛衣",
UI_CUI_TorsoExtra = "躯干扩展",
UI_CUI_SweaterHat = "连帽衣",
UI_CUI_Necklace = "项链",
UI_CUI_Necklace_Long = "长项链",
UI_CUI_Neck = "颈部",
UI_CUI_Nose = "鼻子",
UI_CUI_Ears = "耳部",
UI_CUI_EarTop = "耳上部",
UI_CUI_Right_MiddleFinger = "右中指",
UI_CUI_Left_MiddleFinger = "左中指",
UI_CUI_Right_RingFinger = "右无名指",
UI_CUI_Left_RingFinger = "左无名指",
UI_CUI_RightWrist = "右腕",
UI_CUI_LeftWrist = "左腕",
UI_CUI_BellyButton = "腹部",
UI_CUI_Eyes = "眼睛",
UI_CUI_LeftEye = "左眼",
UI_CUI_RightEye = "右眼",
UI_CUI_Hands = "手",
UI_CUI_Scarf = "围巾",
UI_CUI_Underwear = "内衣",
UI_CUI_MakeUp_FullFace = "面妆",
UI_CUI_MakeUp_Eyes = "眼妆",
UI_CUI_MakeUp_EyesShadow = "眼影",
UI_CUI_MakeUp_Lips = "唇妆",
UI_CUI_Belt = "腰带",
UI_CUI_BeltExtra = "肚脐",
UI_CUI_AmmoStrap = "弹药带",
UI_CUI_Tail = "尾巴",
UI_CUI_Legs1 = "腿部1",
UI_CUI_Pants = "裤子",
UI_CUI_Skirt = "半身裙",
UI_CUI_ShortSleeveShirt = "短袖衬衫",
UI_CUI_Shirt = "衬衫",
UI_CUI_Tshirt = "T恤",
UI_CUI_TankTop = "背心",
UI_CUI_Socks = "袜子",
UI_CUI_UnderwearInner = "内裤",
UI_CUI_Shoes = "鞋",
UI_CUI_Torso1Legs1 = "腿部",
UI_CUI_BathRobe = "浴袍",
UI_CUI_FullSuit = "套装",
UI_CUI_FullSuitHead = "防护衣",
UI_CUI_Dress = "礼服",
UI_CUI_UnderwearTop = "上身内衣",
UI_CUI_UnderwearBottom = "下身内衣",
UI_CUI_UnderwearExtra1 = "内衣额外1",
UI_CUI_UnderwearExtra2 = "内衣额外2",
UI_CUI_ZedDmg = "伤害",
UI_CUI_Bandage = "绷带",
UI_CUI_Wound = "伤口",
}

[I dont know how to use github，sorry]<---- This is his reply too but I think it's does not include in 'UI_CN.txt' I think
Hope this will be help :)

**Comment by petrvecera** [comment]
Thanks, added https://github.com/rempAut/PZ-ClothingUI/pull/21
